import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowUpRight, Database, LockKeyhole } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageIntro, Panel } from '../app/components.js';
import { api } from '../services/api.js';

export function PrivacyPolicyPage() {
  const [operator, setOperator] = useState({
    operatorConfigured: false, operatorLegalName: 'NOT CONFIGURED', operatorServiceAddress: 'NOT CONFIGURED',
    supportConfigured: false, supportContact: 'NOT CONFIGURED',
  });
  useEffect(() => {
    void api.publicConfig().then(setOperator).catch(() => undefined);
  }, []);

  return <>
    <PageIntro eyebrow="PUBLIC NOTICE / PRIVACY" title="Privacy policy" description="A plain-language description of what this AI·FEWS release does with information. This notice reflects the implemented application, not a guarantee of official warnings or a complete legal assessment." action={<Link className="button button-secondary button-compact" to="/privacy">Privacy center</Link>} />
    {(!operator.operatorConfigured || !operator.supportConfigured) && <div className="error-banner policy-readiness" role="alert"><AlertTriangle size={17} aria-hidden="true" /><p><strong>Publication details are incomplete:</strong> legal operator identity/address and support contact must be supplied and reviewed before representing this as a final operator-approved policy or submitting the app to an app store. Current support contact: <strong>{operator.supportContact}</strong>.</p></div>}
    <div className="stack policy-sections">
      <Panel title="1. Who operates AI·FEWS" eyebrow="OPERATOR & CONTACT"><p>AI·FEWS is an environmental decision-support application. {operator.operatorConfigured ? <>The legal service operator is <strong>{operator.operatorLegalName}</strong>, with service address <strong>{operator.operatorServiceAddress}</strong>.</> : <>The legal name and service address of its operator are <strong>NOT CONFIGURED</strong> rather than guessed.</>} For privacy questions or requests, contact: <strong>{operator.supportContact}</strong>.</p><p className="field-hint">Policy reviewed against the current application implementation on 30 September 2026. Publication and jurisdiction-specific legal review by the service operator have not been confirmed. Confirm the contact channel is monitored before public distribution.</p></Panel>
      <Panel title="2. Location and environmental information" eyebrow="WHAT YOU PROVIDE"><p>You may enter latitude/longitude yourself or choose the one-time location action. Device location permission is requested only after that action; AI·FEWS does not run a background location watcher. A name lookup is separate and occurs only when you choose “Resolve place name.”</p><p>When you request weather, rainfall, or air quality, the selected coordinates are sent from the AI·FEWS server to the configured Open-Meteo service. Your observation may be saved to server history only after you explicitly save that place and request an assessment there. Unnamed, unsaved assessments are not written to the saved-location time series.</p></Panel>
      <Panel title="3. Saved places and anonymous installation key" eyebrow="SERVER RECORDS"><p>There is no user login or cross-device account. Your browser/app keeps a random anonymous owner key; requests send it to the AI·FEWS server over the connection. The server derives and stores a keyed hash for ownership checks rather than storing the raw key. Saved place names and coordinates, explicitly requested observation history, resulting alerts, and notification preferences are stored in the managed MySQL database for that installation key.</p><p>Anyone who obtains access to this browser/app installation may use its saved-place identity. Clearing local storage can remove the key and disconnect that installation from its saved server records; it does not delete those server records.</p></Panel>
      <Panel title="4. Community reports" eyebrow="USER-SUBMITTED INFORMATION"><p>Submitting a report sends its selected coordinates, category, description (up to 500 characters), stable client ID, and event time to the backend. Offline reports remain in this device’s IndexedDB queue until sync is confirmed. Reports enter moderation as <strong>PENDING_REVIEW</strong>; a public map query returns verified reports only. A moderation token is not configured, so no verified-report moderation workflow is currently available. The implementation has no user-facing delete control for a report after server sync. For privacy or deletion requests, contact <strong>{operator.supportContact}</strong>; the app itself does not provide self-service deletion of synced reports.</p></Panel>
      <Panel title="5. Notifications, analytics and device data" eyebrow="DEVICE & PREFERENCES"><p>Notification preferences are stored on the backend for the anonymous installation key. Browser or Android notification permission is requested only if you explicitly enable that setting. Persisted in-app alert records are available when you explicitly refresh; the app also attempts device-local notifications after a persisted alert is encountered, but delivery has not been verified on physical Android devices or across browser runtimes. Remote push and background/off-session delivery are not configured.</p><p>The application code does not integrate analytics, advertising, or cross-site tracking. The app stores its offline snapshots, queued reports, and preparedness content in browser/device IndexedDB; selected display/preferences and the owner/API-origin settings use local browser storage.</p></Panel>
      <Panel title="6. Third-party services and infrastructure" eyebrow="RECIPIENTS"><ul className="rule-list"><li><a href="https://open-meteo.com/en/terms" target="_blank" rel="noreferrer">Open-Meteo</a> provides the live forecast and air-quality requests initiated by the server. The service receives query coordinates and normal network/service metadata.</li><li><a href="https://operations.osmfoundation.org/policies/nominatim/" target="_blank" rel="noreferrer">OpenStreetMap Nominatim</a> receives coordinates only for a user-initiated place-name resolution, subject to its public-service usage policy. Lookups are throttled and briefly cached.</li><li>Visible <a href="https://operations.osmfoundation.org/policies/tiles/" target="_blank" rel="noreferrer">OpenStreetMap map tiles</a> are requested directly by your device. This reveals the requested tile area and ordinary network metadata to that service. Tiles are not prefetched or cached for offline use.</li><li>The application is hosted using Manus/Webdev infrastructure with a managed MySQL database. Hosting providers may process standard service/network metadata under their own terms. AI·FEWS application error logs are designed not to include raw request coordinates, report bodies, owner keys, moderation credentials, or database connection strings.</li></ul><p className="field-hint">External providers have their own privacy and retention terms. Follow the links above for provider-specific information.</p></Panel>
      <Panel title="7. Retention and deletion" eyebrow="HOW LONG / YOUR CONTROLS"><p>Trend history is queried for a 90-day window and older observations for a saved place are pruned when that place is next assessed. Reports older than 90 days are pruned during a report-list request. Alerts are shown while unexpired and records more than 30 days past expiry are pruned during an alert-list request. No scheduled cleanup is configured; physical deletion may be delayed when these requests do not run. These are application cleanup rules, not a guaranteed service-level deletion deadline.</p><p>The Privacy Center can erase local snapshots, queued reports, cached preparedness data, and local preferences. It clearly does not erase server data. Deleting a saved place is a separate confirmed action and cascades its linked server snapshots and alerts; server-side notification preferences and community reports are not thereby deleted. Synced reports have no in-app user deletion feature. For privacy or deletion questions, contact <strong>{operator.supportContact}</strong>.</p></Panel>
      <Panel title="8. Offline use, security and changes" eyebrow="YOUR CHOICES"><p>The service worker caches the application shell and versioned app assets only. It does not cache API responses or map tiles. A locally retained environmental snapshot is labeled with its original source time and a non-live status. This application provides decision support, not official warnings; follow local emergency services and authorities.</p><p>Requests use HTTPS in production, validated shared API contracts, bounded inputs, rate limiting, private no-store API responses and parameterized database statements. Moderation is disabled until the service owner configures its server-only credential. No measure guarantees security. The owner may update this notice when the product’s practices change; check the dated copy and contact the operator with questions.</p></Panel>
      <div className="privacy-policy-footnote"><Database size={15} aria-hidden="true" /><span>This policy is published at the public HTTPS route <code>/privacy-policy</code> when the site is deployed.</span><a href="https://open-meteo.com/en/privacy-policy" target="_blank" rel="noreferrer">Open-Meteo privacy <ArrowUpRight size={13} aria-hidden="true" /></a><LockKeyhole size={15} aria-hidden="true" /></div>
    </div>
  </>;
}
